# Individual Assignment

This individual assignment is to get you to practice Shiny on your own but using a different programming language.

- If your group project is done in Shiny for Python, you will use Shiny for R
- If your group project is done in [Shiny for R](https://shiny.posit.co/r/getstarted/shiny-basics/lesson1/), you will use Shiny for Python

> If you want to use another dashboarding framework talk with your instructor first.

You application will be based on your current group project;
you shoudl be able to borrow most of your current project as a reference.

Your new application will re-implmeent your current application but have at least the following features:

1. At least 1 input component (e.g., slider, dropdown, radio button, etc)
2. At least 1 reactive calc (e.g., a dataframe)
3. At least 2 output components (e.g., valueboxes, plots, tables, maps, etc)

Since this is an individual assignment,
you will deploy this application in your own Posit Connect Cloud instance along with the (public) github repository.

Your repository will have a `README.md` file that will describe how to install packages and run your application.
The About section metadata will also have a link to your deployed applicaiton.

You may create this repository in your own personal github account.
